name: CI for the second SWE project.
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event." |
          echo "OS ${{ runner.os }}" |
          echo "Branch ${{ github.ref }}, repository ${{ github.repository }}."

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm i

      - name: Checking errors with ESLint
        run: |
          npm run eslint

      - name: Checking errors with stylelint
        run: |
          npm run stylelint

      - name: Building application
        run: |
          npm run build
